version: '3.8'

services:
  backend:
    # Pulls the pre-built backend image from your Docker Hub account
    image: sujal0574/faceai-backend:latest
    container_name: faceai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./hrms.db:/app/hrms.db
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    # Pulls the pre-built frontend image from Docker Hub
    image: sujal0574/faceai-frontend:latest
    container_name: faceai-frontend
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend

  admin-dashboard:
    # Pulls the pre-built admin-dashboard image from Docker Hub
    image: sujal0574/faceai-admin-dashboard:latest
    container_name: faceai-admin-dashboard
    ports:
      - "5174:80"
    restart: always
    depends_on:
      - backend

  ngrok:
    # Automatically creates a secure HTTPS tunnel so mobile cameras work!
    image: ngrok/ngrok:latest
    container_name: faceai-ngrok
    environment:
      - NGROK_AUTHTOKEN=390rAsHTph5aHs9EfximIknu1Te_ZHaX1Z2oic3XFD4HFexD
    command:
      - "http"
      - "http://backend:8000"
    ports:
      - "4040:4040"
    restart: always
    depends_on:
      - backend
